export const MILLISECOND = 1000;
export const SECOND = 60;
export const MINUTE = 60;
export const HOUR = 24;

export const DAY_AS_MILLISECOND = MILLISECOND * SECOND * MINUTE * HOUR;
export const HOUR_AS_MILLISECOND = MILLISECOND * SECOND * MINUTE;
export const MINUTE_AS_MILLISECOND = MILLISECOND * SECOND;
